<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Mail.aspx.cs" Inherits="Dating.MyPages.Mail" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

    <div id="bigbox">
        <div id="littlebox1">
        
            <asp:GridView ID="gdMail" runat="server" AutoGenerateColumns="False" 
                AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" 
                onselectedindexchanged="gdMail_SelectedIndexChanged" 
                onrowdeleting="gdMail_RowDeleting" PageSize="5" AllowPaging="True" 
                BorderStyle="Inset" GridLines="None" Height="200px" 
                onpageindexchanging="gdMail_PageIndexChanging" Width="450px"
                ShowHeaderWhenEmpty="true">
                <Columns>
                    <asp:BoundField DataField="Amne" HeaderText="Subject" />
                    <asp:BoundField DataField="Fran" HeaderText="From" />
                    <asp:BoundField DataField="Skickat" HeaderText="Date" />
                    <asp:BoundField DataField="InneHall" HeaderText="Body" 
                        ItemStyle-CssClass="Hidden" HeaderStyle-CssClass="Hidden">
                
                        <HeaderStyle CssClass="Hidden"></HeaderStyle>

                        <ItemStyle CssClass="Hidden"></ItemStyle>
                    </asp:BoundField>
                    <asp:BoundField DataField="MedID" HeaderText="ID" ItemStyle-CssClass="Hidden" HeaderStyle-CssClass="Hidden" />
                
                </Columns>
            </asp:GridView>
        <br />

        <asp:LoginView runat="server" ID="logViewMail">
            <RoleGroups>
                <asp:RoleGroup Roles="standard">
                    <ContentTemplate>
                        <asp:TextBox ID="txtNoAccess" runat="server" Height="288px" Width="465px" BorderStyle="None" ReadOnly="true" 
                                     TextMode="MultiLine">To read messages you have to upgrade to premium membership</asp:TextBox>
                    </ContentTemplate>
                </asp:RoleGroup>
                <asp:RoleGroup Roles="premium">
                    <ContentTemplate>
                        <asp:TextBox ID="txtMail" runat="server" Height="288px" Width="465px" 
                                     BorderStyle="None" ReadOnly="True" TextMode="MultiLine"></asp:TextBox>
                    </ContentTemplate>
                </asp:RoleGroup>
            </RoleGroups> 
        </asp:LoginView>

    </div>
   <div id="littlebox2">
       <br />
       
       <asp:Panel ID="Panel1" runat="server" GroupingText="Send" Height="475px" 
           Width="536px">
           <asp:Label ID="lblTo" runat="server" Text="To:"></asp:Label>
           <br />
           <asp:TextBox ID="txtTo" runat="server" Width="231px"></asp:TextBox>
           <asp:Label ID="lblErrorMessageTo" runat="server" Text=""></asp:Label>
           <br />
           <asp:Label ID="lblSubject" runat="server" Text="Subject:"></asp:Label><br />
           <asp:TextBox ID="txtSubject" runat="server" Width="231px"></asp:TextBox>
           <br />
           <asp:Label ID="lblMessage" runat="server" Text="Message:"></asp:Label><br />
           <asp:TextBox ID="txtMessage" runat="server" Height="230px" TextMode="MultiLine" 
               Width="523px" ValidationGroup="sendMail"></asp:TextBox>
           <br />
           <span class="errorBox">
                <asp:RequiredFieldValidator runat="server" ID="rfvCheckMessage" ControlToValidate="txtMessage" Display="Dynamic"
                    ErrorMessage="Leave a message" ValidationGroup="sendMail">
                </asp:RequiredFieldValidator>
                <asp:RegularExpressionValidator runat="server" ID="revCheckMessage" ControlToValidate="txtMessage" Display="Dynamic"
                    ErrorMessage="Message must be between 20 - 500 characters in lenght" ValidationExpression="^.{20,500}$" ValidationGroup="sendMail">
                </asp:RegularExpressionValidator>
           </span>
           <br />
           <asp:Button ID="Button1" runat="server" Height="59px" onclick="Button1_Click" 
               Text="Send" Width="104px" ValidationGroup="sendMail" />
           <br />
       </asp:Panel>
        </div>

   </div>
</asp:Content>
