//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("App_DatingsystemModel", "FK__Inlagg__Fran__0AD2A005", "Anvandare", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(wcf.Anvandare), "Inlagg", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(wcf.Inlagg), true)]
[assembly: EdmRelationshipAttribute("App_DatingsystemModel", "FK__Inlagg__Till__0BC6C43E", "Anvandare", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(wcf.Anvandare), "Inlagg", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(wcf.Inlagg), true)]
[assembly: EdmRelationshipAttribute("App_DatingsystemModel", "FK__Kontakter__Anvan__15502E78", "Anvandare", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(wcf.Anvandare), "Kontakter", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(wcf.Kontakter), true)]
[assembly: EdmRelationshipAttribute("App_DatingsystemModel", "FK__Kontakter__Konta__164452B1", "Anvandare", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(wcf.Anvandare), "Kontakter", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(wcf.Kontakter), true)]
[assembly: EdmRelationshipAttribute("App_DatingsystemModel", "FK__Meddelande__Fran__0519C6AF", "Anvandare", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(wcf.Anvandare), "Meddelande", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(wcf.Meddelande), true)]
[assembly: EdmRelationshipAttribute("App_DatingsystemModel", "FK__Meddelande__Till__060DEAE8", "Anvandare", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(wcf.Anvandare), "Meddelande", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(wcf.Meddelande), true)]
[assembly: EdmRelationshipAttribute("App_DatingsystemModel", "FK__ProfilBil__Anvan__108B795B", "Anvandare", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(wcf.Anvandare), "ProfilBild", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(wcf.ProfilBild), true)]

#endregion

namespace wcf
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DatingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DatingEntities object using the connection string found in the 'DatingEntities' section of the application configuration file.
        /// </summary>
        public DatingEntities() : base("name=DatingEntities", "DatingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatingEntities object.
        /// </summary>
        public DatingEntities(string connectionString) : base(connectionString, "DatingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatingEntities object.
        /// </summary>
        public DatingEntities(EntityConnection connection) : base(connection, "DatingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Anvandare> Anvandare
        {
            get
            {
                if ((_Anvandare == null))
                {
                    _Anvandare = base.CreateObjectSet<Anvandare>("Anvandare");
                }
                return _Anvandare;
            }
        }
        private ObjectSet<Anvandare> _Anvandare;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Inlagg> Inlagg
        {
            get
            {
                if ((_Inlagg == null))
                {
                    _Inlagg = base.CreateObjectSet<Inlagg>("Inlagg");
                }
                return _Inlagg;
            }
        }
        private ObjectSet<Inlagg> _Inlagg;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Kontakter> Kontakter
        {
            get
            {
                if ((_Kontakter == null))
                {
                    _Kontakter = base.CreateObjectSet<Kontakter>("Kontakter");
                }
                return _Kontakter;
            }
        }
        private ObjectSet<Kontakter> _Kontakter;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Meddelande> Meddelande
        {
            get
            {
                if ((_Meddelande == null))
                {
                    _Meddelande = base.CreateObjectSet<Meddelande>("Meddelande");
                }
                return _Meddelande;
            }
        }
        private ObjectSet<Meddelande> _Meddelande;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProfilBild> ProfilBild
        {
            get
            {
                if ((_ProfilBild == null))
                {
                    _ProfilBild = base.CreateObjectSet<ProfilBild>("ProfilBild");
                }
                return _ProfilBild;
            }
        }
        private ObjectSet<ProfilBild> _ProfilBild;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Anvandare EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAnvandare(Anvandare anvandare)
        {
            base.AddObject("Anvandare", anvandare);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Inlagg EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInlagg(Inlagg inlagg)
        {
            base.AddObject("Inlagg", inlagg);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Kontakter EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKontakter(Kontakter kontakter)
        {
            base.AddObject("Kontakter", kontakter);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Meddelande EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMeddelande(Meddelande meddelande)
        {
            base.AddObject("Meddelande", meddelande);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProfilBild EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProfilBild(ProfilBild profilBild)
        {
            base.AddObject("ProfilBild", profilBild);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="App_DatingsystemModel", Name="Anvandare")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Anvandare : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Anvandare object.
        /// </summary>
        /// <param name="profilNamn">Initial value of the ProfilNamn property.</param>
        public static Anvandare CreateAnvandare(global::System.String profilNamn)
        {
            Anvandare anvandare = new Anvandare();
            anvandare.ProfilNamn = profilNamn;
            return anvandare;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProfilNamn
        {
            get
            {
                return _ProfilNamn;
            }
            set
            {
                if (_ProfilNamn != value)
                {
                    OnProfilNamnChanging(value);
                    ReportPropertyChanging("ProfilNamn");
                    _ProfilNamn = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ProfilNamn");
                    OnProfilNamnChanged();
                }
            }
        }
        private global::System.String _ProfilNamn;
        partial void OnProfilNamnChanging(global::System.String value);
        partial void OnProfilNamnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fornamn
        {
            get
            {
                return _Fornamn;
            }
            set
            {
                OnFornamnChanging(value);
                ReportPropertyChanging("Fornamn");
                _Fornamn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fornamn");
                OnFornamnChanged();
            }
        }
        private global::System.String _Fornamn;
        partial void OnFornamnChanging(global::System.String value);
        partial void OnFornamnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Efternamn
        {
            get
            {
                return _Efternamn;
            }
            set
            {
                OnEfternamnChanging(value);
                ReportPropertyChanging("Efternamn");
                _Efternamn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Efternamn");
                OnEfternamnChanged();
            }
        }
        private global::System.String _Efternamn;
        partial void OnEfternamnChanging(global::System.String value);
        partial void OnEfternamnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Alder
        {
            get
            {
                return _Alder;
            }
            set
            {
                OnAlderChanging(value);
                ReportPropertyChanging("Alder");
                _Alder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Alder");
                OnAlderChanged();
            }
        }
        private Nullable<global::System.Int32> _Alder;
        partial void OnAlderChanging(Nullable<global::System.Int32> value);
        partial void OnAlderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Kon
        {
            get
            {
                return _Kon;
            }
            set
            {
                OnKonChanging(value);
                ReportPropertyChanging("Kon");
                _Kon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Kon");
                OnKonChanged();
            }
        }
        private global::System.String _Kon;
        partial void OnKonChanging(global::System.String value);
        partial void OnKonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Info
        {
            get
            {
                return _Info;
            }
            set
            {
                OnInfoChanging(value);
                ReportPropertyChanging("Info");
                _Info = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Info");
                OnInfoChanged();
            }
        }
        private global::System.String _Info;
        partial void OnInfoChanging(global::System.String value);
        partial void OnInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ort
        {
            get
            {
                return _Ort;
            }
            set
            {
                OnOrtChanging(value);
                ReportPropertyChanging("Ort");
                _Ort = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ort");
                OnOrtChanged();
            }
        }
        private global::System.String _Ort;
        partial void OnOrtChanging(global::System.String value);
        partial void OnOrtChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("App_DatingsystemModel", "FK__Inlagg__Fran__0AD2A005", "Inlagg")]
        public EntityCollection<Inlagg> Inlagg
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Inlagg>("App_DatingsystemModel.FK__Inlagg__Fran__0AD2A005", "Inlagg");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Inlagg>("App_DatingsystemModel.FK__Inlagg__Fran__0AD2A005", "Inlagg", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("App_DatingsystemModel", "FK__Inlagg__Till__0BC6C43E", "Inlagg")]
        public EntityCollection<Inlagg> Inlagg1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Inlagg>("App_DatingsystemModel.FK__Inlagg__Till__0BC6C43E", "Inlagg");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Inlagg>("App_DatingsystemModel.FK__Inlagg__Till__0BC6C43E", "Inlagg", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("App_DatingsystemModel", "FK__Kontakter__Anvan__15502E78", "Kontakter")]
        public EntityCollection<Kontakter> Kontakter
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Kontakter>("App_DatingsystemModel.FK__Kontakter__Anvan__15502E78", "Kontakter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Kontakter>("App_DatingsystemModel.FK__Kontakter__Anvan__15502E78", "Kontakter", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("App_DatingsystemModel", "FK__Kontakter__Konta__164452B1", "Kontakter")]
        public EntityCollection<Kontakter> Kontakter1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Kontakter>("App_DatingsystemModel.FK__Kontakter__Konta__164452B1", "Kontakter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Kontakter>("App_DatingsystemModel.FK__Kontakter__Konta__164452B1", "Kontakter", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("App_DatingsystemModel", "FK__Meddelande__Fran__0519C6AF", "Meddelande")]
        public EntityCollection<Meddelande> Meddelande
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Meddelande>("App_DatingsystemModel.FK__Meddelande__Fran__0519C6AF", "Meddelande");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Meddelande>("App_DatingsystemModel.FK__Meddelande__Fran__0519C6AF", "Meddelande", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("App_DatingsystemModel", "FK__Meddelande__Till__060DEAE8", "Meddelande")]
        public EntityCollection<Meddelande> Meddelande1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Meddelande>("App_DatingsystemModel.FK__Meddelande__Till__060DEAE8", "Meddelande");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Meddelande>("App_DatingsystemModel.FK__Meddelande__Till__060DEAE8", "Meddelande", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("App_DatingsystemModel", "FK__ProfilBil__Anvan__108B795B", "ProfilBild")]
        public EntityCollection<ProfilBild> ProfilBild
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProfilBild>("App_DatingsystemModel.FK__ProfilBil__Anvan__108B795B", "ProfilBild");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProfilBild>("App_DatingsystemModel.FK__ProfilBil__Anvan__108B795B", "ProfilBild", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="App_DatingsystemModel", Name="Inlagg")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Inlagg : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Inlagg object.
        /// </summary>
        /// <param name="inlaggID">Initial value of the InlaggID property.</param>
        /// <param name="fran">Initial value of the Fran property.</param>
        /// <param name="till">Initial value of the Till property.</param>
        /// <param name="innehall">Initial value of the Innehall property.</param>
        public static Inlagg CreateInlagg(global::System.Int32 inlaggID, global::System.String fran, global::System.String till, global::System.String innehall)
        {
            Inlagg inlagg = new Inlagg();
            inlagg.InlaggID = inlaggID;
            inlagg.Fran = fran;
            inlagg.Till = till;
            inlagg.Innehall = innehall;
            return inlagg;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InlaggID
        {
            get
            {
                return _InlaggID;
            }
            set
            {
                if (_InlaggID != value)
                {
                    OnInlaggIDChanging(value);
                    ReportPropertyChanging("InlaggID");
                    _InlaggID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("InlaggID");
                    OnInlaggIDChanged();
                }
            }
        }
        private global::System.Int32 _InlaggID;
        partial void OnInlaggIDChanging(global::System.Int32 value);
        partial void OnInlaggIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Fran
        {
            get
            {
                return _Fran;
            }
            set
            {
                OnFranChanging(value);
                ReportPropertyChanging("Fran");
                _Fran = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Fran");
                OnFranChanged();
            }
        }
        private global::System.String _Fran;
        partial void OnFranChanging(global::System.String value);
        partial void OnFranChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Till
        {
            get
            {
                return _Till;
            }
            set
            {
                OnTillChanging(value);
                ReportPropertyChanging("Till");
                _Till = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Till");
                OnTillChanged();
            }
        }
        private global::System.String _Till;
        partial void OnTillChanging(global::System.String value);
        partial void OnTillChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Innehall
        {
            get
            {
                return _Innehall;
            }
            set
            {
                OnInnehallChanging(value);
                ReportPropertyChanging("Innehall");
                _Innehall = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Innehall");
                OnInnehallChanged();
            }
        }
        private global::System.String _Innehall;
        partial void OnInnehallChanging(global::System.String value);
        partial void OnInnehallChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Skickat
        {
            get
            {
                return _Skickat;
            }
            set
            {
                OnSkickatChanging(value);
                ReportPropertyChanging("Skickat");
                _Skickat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Skickat");
                OnSkickatChanged();
            }
        }
        private Nullable<global::System.DateTime> _Skickat;
        partial void OnSkickatChanging(Nullable<global::System.DateTime> value);
        partial void OnSkickatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HarLast
        {
            get
            {
                return _HarLast;
            }
            set
            {
                OnHarLastChanging(value);
                ReportPropertyChanging("HarLast");
                _HarLast = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HarLast");
                OnHarLastChanged();
            }
        }
        private Nullable<global::System.Int32> _HarLast;
        partial void OnHarLastChanging(Nullable<global::System.Int32> value);
        partial void OnHarLastChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("App_DatingsystemModel", "FK__Inlagg__Fran__0AD2A005", "Anvandare")]
        public Anvandare Anvandare
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Inlagg__Fran__0AD2A005", "Anvandare").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Inlagg__Fran__0AD2A005", "Anvandare").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Anvandare> AnvandareReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Inlagg__Fran__0AD2A005", "Anvandare");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Anvandare>("App_DatingsystemModel.FK__Inlagg__Fran__0AD2A005", "Anvandare", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("App_DatingsystemModel", "FK__Inlagg__Till__0BC6C43E", "Anvandare")]
        public Anvandare Anvandare1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Inlagg__Till__0BC6C43E", "Anvandare").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Inlagg__Till__0BC6C43E", "Anvandare").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Anvandare> Anvandare1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Inlagg__Till__0BC6C43E", "Anvandare");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Anvandare>("App_DatingsystemModel.FK__Inlagg__Till__0BC6C43E", "Anvandare", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="App_DatingsystemModel", Name="Kontakter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kontakter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Kontakter object.
        /// </summary>
        /// <param name="anvandare">Initial value of the Anvandare property.</param>
        /// <param name="kontakt">Initial value of the Kontakt property.</param>
        public static Kontakter CreateKontakter(global::System.String anvandare, global::System.String kontakt)
        {
            Kontakter kontakter = new Kontakter();
            kontakter.Anvandare = anvandare;
            kontakter.Kontakt = kontakt;
            return kontakter;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Anvandare
        {
            get
            {
                return _Anvandare;
            }
            set
            {
                if (_Anvandare != value)
                {
                    OnAnvandareChanging(value);
                    ReportPropertyChanging("Anvandare");
                    _Anvandare = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Anvandare");
                    OnAnvandareChanged();
                }
            }
        }
        private global::System.String _Anvandare;
        partial void OnAnvandareChanging(global::System.String value);
        partial void OnAnvandareChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Request
        {
            get
            {
                return _Request;
            }
            set
            {
                OnRequestChanging(value);
                ReportPropertyChanging("Request");
                _Request = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Request");
                OnRequestChanged();
            }
        }
        private Nullable<global::System.Int32> _Request;
        partial void OnRequestChanging(Nullable<global::System.Int32> value);
        partial void OnRequestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Kontakt
        {
            get
            {
                return _Kontakt;
            }
            set
            {
                if (_Kontakt != value)
                {
                    OnKontaktChanging(value);
                    ReportPropertyChanging("Kontakt");
                    _Kontakt = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Kontakt");
                    OnKontaktChanged();
                }
            }
        }
        private global::System.String _Kontakt;
        partial void OnKontaktChanging(global::System.String value);
        partial void OnKontaktChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("App_DatingsystemModel", "FK__Kontakter__Anvan__15502E78", "Anvandare")]
        public Anvandare Anvandare1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Kontakter__Anvan__15502E78", "Anvandare").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Kontakter__Anvan__15502E78", "Anvandare").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Anvandare> Anvandare1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Kontakter__Anvan__15502E78", "Anvandare");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Anvandare>("App_DatingsystemModel.FK__Kontakter__Anvan__15502E78", "Anvandare", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("App_DatingsystemModel", "FK__Kontakter__Konta__164452B1", "Anvandare")]
        public Anvandare Anvandare2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Kontakter__Konta__164452B1", "Anvandare").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Kontakter__Konta__164452B1", "Anvandare").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Anvandare> Anvandare2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Kontakter__Konta__164452B1", "Anvandare");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Anvandare>("App_DatingsystemModel.FK__Kontakter__Konta__164452B1", "Anvandare", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="App_DatingsystemModel", Name="Meddelande")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Meddelande : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Meddelande object.
        /// </summary>
        /// <param name="medID">Initial value of the MedID property.</param>
        /// <param name="fran">Initial value of the Fran property.</param>
        /// <param name="till">Initial value of the Till property.</param>
        /// <param name="innehall">Initial value of the Innehall property.</param>
        public static Meddelande CreateMeddelande(global::System.Int32 medID, global::System.String fran, global::System.String till, global::System.String innehall)
        {
            Meddelande meddelande = new Meddelande();
            meddelande.MedID = medID;
            meddelande.Fran = fran;
            meddelande.Till = till;
            meddelande.Innehall = innehall;
            return meddelande;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MedID
        {
            get
            {
                return _MedID;
            }
            set
            {
                if (_MedID != value)
                {
                    OnMedIDChanging(value);
                    ReportPropertyChanging("MedID");
                    _MedID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MedID");
                    OnMedIDChanged();
                }
            }
        }
        private global::System.Int32 _MedID;
        partial void OnMedIDChanging(global::System.Int32 value);
        partial void OnMedIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Fran
        {
            get
            {
                return _Fran;
            }
            set
            {
                OnFranChanging(value);
                ReportPropertyChanging("Fran");
                _Fran = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Fran");
                OnFranChanged();
            }
        }
        private global::System.String _Fran;
        partial void OnFranChanging(global::System.String value);
        partial void OnFranChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Till
        {
            get
            {
                return _Till;
            }
            set
            {
                OnTillChanging(value);
                ReportPropertyChanging("Till");
                _Till = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Till");
                OnTillChanged();
            }
        }
        private global::System.String _Till;
        partial void OnTillChanging(global::System.String value);
        partial void OnTillChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Amne
        {
            get
            {
                return _Amne;
            }
            set
            {
                OnAmneChanging(value);
                ReportPropertyChanging("Amne");
                _Amne = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Amne");
                OnAmneChanged();
            }
        }
        private global::System.String _Amne;
        partial void OnAmneChanging(global::System.String value);
        partial void OnAmneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Innehall
        {
            get
            {
                return _Innehall;
            }
            set
            {
                OnInnehallChanging(value);
                ReportPropertyChanging("Innehall");
                _Innehall = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Innehall");
                OnInnehallChanged();
            }
        }
        private global::System.String _Innehall;
        partial void OnInnehallChanging(global::System.String value);
        partial void OnInnehallChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Skickat
        {
            get
            {
                return _Skickat;
            }
            set
            {
                OnSkickatChanging(value);
                ReportPropertyChanging("Skickat");
                _Skickat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Skickat");
                OnSkickatChanged();
            }
        }
        private Nullable<global::System.DateTime> _Skickat;
        partial void OnSkickatChanging(Nullable<global::System.DateTime> value);
        partial void OnSkickatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HarLast
        {
            get
            {
                return _HarLast;
            }
            set
            {
                OnHarLastChanging(value);
                ReportPropertyChanging("HarLast");
                _HarLast = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HarLast");
                OnHarLastChanged();
            }
        }
        private Nullable<global::System.Int32> _HarLast;
        partial void OnHarLastChanging(Nullable<global::System.Int32> value);
        partial void OnHarLastChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("App_DatingsystemModel", "FK__Meddelande__Fran__0519C6AF", "Anvandare")]
        public Anvandare Anvandare
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Meddelande__Fran__0519C6AF", "Anvandare").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Meddelande__Fran__0519C6AF", "Anvandare").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Anvandare> AnvandareReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Meddelande__Fran__0519C6AF", "Anvandare");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Anvandare>("App_DatingsystemModel.FK__Meddelande__Fran__0519C6AF", "Anvandare", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("App_DatingsystemModel", "FK__Meddelande__Till__060DEAE8", "Anvandare")]
        public Anvandare Anvandare1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Meddelande__Till__060DEAE8", "Anvandare").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Meddelande__Till__060DEAE8", "Anvandare").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Anvandare> Anvandare1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__Meddelande__Till__060DEAE8", "Anvandare");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Anvandare>("App_DatingsystemModel.FK__Meddelande__Till__060DEAE8", "Anvandare", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="App_DatingsystemModel", Name="ProfilBild")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProfilBild : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProfilBild object.
        /// </summary>
        /// <param name="bildID">Initial value of the BildID property.</param>
        /// <param name="anvandare">Initial value of the Anvandare property.</param>
        public static ProfilBild CreateProfilBild(global::System.Int32 bildID, global::System.String anvandare)
        {
            ProfilBild profilBild = new ProfilBild();
            profilBild.BildID = bildID;
            profilBild.Anvandare = anvandare;
            return profilBild;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BildID
        {
            get
            {
                return _BildID;
            }
            set
            {
                if (_BildID != value)
                {
                    OnBildIDChanging(value);
                    ReportPropertyChanging("BildID");
                    _BildID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BildID");
                    OnBildIDChanged();
                }
            }
        }
        private global::System.Int32 _BildID;
        partial void OnBildIDChanging(global::System.Int32 value);
        partial void OnBildIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bild
        {
            get
            {
                return _Bild;
            }
            set
            {
                OnBildChanging(value);
                ReportPropertyChanging("Bild");
                _Bild = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bild");
                OnBildChanged();
            }
        }
        private global::System.String _Bild;
        partial void OnBildChanging(global::System.String value);
        partial void OnBildChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Anvandare
        {
            get
            {
                return _Anvandare;
            }
            set
            {
                OnAnvandareChanging(value);
                ReportPropertyChanging("Anvandare");
                _Anvandare = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Anvandare");
                OnAnvandareChanged();
            }
        }
        private global::System.String _Anvandare;
        partial void OnAnvandareChanging(global::System.String value);
        partial void OnAnvandareChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("App_DatingsystemModel", "FK__ProfilBil__Anvan__108B795B", "Anvandare")]
        public Anvandare Anvandare1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__ProfilBil__Anvan__108B795B", "Anvandare").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__ProfilBil__Anvan__108B795B", "Anvandare").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Anvandare> Anvandare1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Anvandare>("App_DatingsystemModel.FK__ProfilBil__Anvan__108B795B", "Anvandare");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Anvandare>("App_DatingsystemModel.FK__ProfilBil__Anvan__108B795B", "Anvandare", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
