//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dating.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inlagg", Namespace="http://schemas.datacontract.org/2004/07/wcf", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Inlagg : Dating.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.Anvandare AnvandareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.Anvandare Anvandare1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR Anvandare1ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR AnvandareReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FranField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HarLastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InlaggIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InnehallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SkickatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TillField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.Anvandare Anvandare {
            get {
                return this.AnvandareField;
            }
            set {
                if ((object.ReferenceEquals(this.AnvandareField, value) != true)) {
                    this.AnvandareField = value;
                    this.RaisePropertyChanged("Anvandare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.Anvandare Anvandare1 {
            get {
                return this.Anvandare1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Anvandare1Field, value) != true)) {
                    this.Anvandare1Field = value;
                    this.RaisePropertyChanged("Anvandare1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR Anvandare1Reference {
            get {
                return this.Anvandare1ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.Anvandare1ReferenceField, value) != true)) {
                    this.Anvandare1ReferenceField = value;
                    this.RaisePropertyChanged("Anvandare1Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR AnvandareReference {
            get {
                return this.AnvandareReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.AnvandareReferenceField, value) != true)) {
                    this.AnvandareReferenceField = value;
                    this.RaisePropertyChanged("AnvandareReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fran {
            get {
                return this.FranField;
            }
            set {
                if ((object.ReferenceEquals(this.FranField, value) != true)) {
                    this.FranField = value;
                    this.RaisePropertyChanged("Fran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HarLast {
            get {
                return this.HarLastField;
            }
            set {
                if ((this.HarLastField.Equals(value) != true)) {
                    this.HarLastField = value;
                    this.RaisePropertyChanged("HarLast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InlaggID {
            get {
                return this.InlaggIDField;
            }
            set {
                if ((this.InlaggIDField.Equals(value) != true)) {
                    this.InlaggIDField = value;
                    this.RaisePropertyChanged("InlaggID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Innehall {
            get {
                return this.InnehallField;
            }
            set {
                if ((object.ReferenceEquals(this.InnehallField, value) != true)) {
                    this.InnehallField = value;
                    this.RaisePropertyChanged("Innehall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Skickat {
            get {
                return this.SkickatField;
            }
            set {
                if ((this.SkickatField.Equals(value) != true)) {
                    this.SkickatField = value;
                    this.RaisePropertyChanged("Skickat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Till {
            get {
                return this.TillField;
            }
            set {
                if ((object.ReferenceEquals(this.TillField, value) != true)) {
                    this.TillField = value;
                    this.RaisePropertyChanged("Till");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.Anvandare))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.Kontakter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.Meddelande))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.ProfilBild))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.Inlagg))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.Anvandare))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.Kontakter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.Meddelande))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.ProfilBild))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.Inlagg))]
    public partial class EntityObject : Dating.ServiceReference1.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Anvandare", Namespace="http://schemas.datacontract.org/2004/07/wcf", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Anvandare : Dating.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AlderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EfternamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FornamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.Inlagg[] InlaggField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.Inlagg[] Inlagg1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.Kontakter[] KontakterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.Kontakter[] Kontakter1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.Meddelande[] MeddelandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.Meddelande[] Meddelande1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.ProfilBild[] ProfilBildField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilNamnField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Alder {
            get {
                return this.AlderField;
            }
            set {
                if ((this.AlderField.Equals(value) != true)) {
                    this.AlderField = value;
                    this.RaisePropertyChanged("Alder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Efternamn {
            get {
                return this.EfternamnField;
            }
            set {
                if ((object.ReferenceEquals(this.EfternamnField, value) != true)) {
                    this.EfternamnField = value;
                    this.RaisePropertyChanged("Efternamn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fornamn {
            get {
                return this.FornamnField;
            }
            set {
                if ((object.ReferenceEquals(this.FornamnField, value) != true)) {
                    this.FornamnField = value;
                    this.RaisePropertyChanged("Fornamn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.Inlagg[] Inlagg {
            get {
                return this.InlaggField;
            }
            set {
                if ((object.ReferenceEquals(this.InlaggField, value) != true)) {
                    this.InlaggField = value;
                    this.RaisePropertyChanged("Inlagg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.Inlagg[] Inlagg1 {
            get {
                return this.Inlagg1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Inlagg1Field, value) != true)) {
                    this.Inlagg1Field = value;
                    this.RaisePropertyChanged("Inlagg1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kon {
            get {
                return this.KonField;
            }
            set {
                if ((object.ReferenceEquals(this.KonField, value) != true)) {
                    this.KonField = value;
                    this.RaisePropertyChanged("Kon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.Kontakter[] Kontakter {
            get {
                return this.KontakterField;
            }
            set {
                if ((object.ReferenceEquals(this.KontakterField, value) != true)) {
                    this.KontakterField = value;
                    this.RaisePropertyChanged("Kontakter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.Kontakter[] Kontakter1 {
            get {
                return this.Kontakter1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Kontakter1Field, value) != true)) {
                    this.Kontakter1Field = value;
                    this.RaisePropertyChanged("Kontakter1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.Meddelande[] Meddelande {
            get {
                return this.MeddelandeField;
            }
            set {
                if ((object.ReferenceEquals(this.MeddelandeField, value) != true)) {
                    this.MeddelandeField = value;
                    this.RaisePropertyChanged("Meddelande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.Meddelande[] Meddelande1 {
            get {
                return this.Meddelande1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Meddelande1Field, value) != true)) {
                    this.Meddelande1Field = value;
                    this.RaisePropertyChanged("Meddelande1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ort {
            get {
                return this.OrtField;
            }
            set {
                if ((object.ReferenceEquals(this.OrtField, value) != true)) {
                    this.OrtField = value;
                    this.RaisePropertyChanged("Ort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.ProfilBild[] ProfilBild {
            get {
                return this.ProfilBildField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilBildField, value) != true)) {
                    this.ProfilBildField = value;
                    this.RaisePropertyChanged("ProfilBild");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilNamn {
            get {
                return this.ProfilNamnField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilNamnField, value) != true)) {
                    this.ProfilNamnField = value;
                    this.RaisePropertyChanged("ProfilNamn");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kontakter", Namespace="http://schemas.datacontract.org/2004/07/wcf", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Kontakter : Dating.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnvandareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.Anvandare Anvandare1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR Anvandare1ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.Anvandare Anvandare2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR Anvandare2ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KontaktField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RequestField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anvandare {
            get {
                return this.AnvandareField;
            }
            set {
                if ((object.ReferenceEquals(this.AnvandareField, value) != true)) {
                    this.AnvandareField = value;
                    this.RaisePropertyChanged("Anvandare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.Anvandare Anvandare1 {
            get {
                return this.Anvandare1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Anvandare1Field, value) != true)) {
                    this.Anvandare1Field = value;
                    this.RaisePropertyChanged("Anvandare1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR Anvandare1Reference {
            get {
                return this.Anvandare1ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.Anvandare1ReferenceField, value) != true)) {
                    this.Anvandare1ReferenceField = value;
                    this.RaisePropertyChanged("Anvandare1Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.Anvandare Anvandare2 {
            get {
                return this.Anvandare2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Anvandare2Field, value) != true)) {
                    this.Anvandare2Field = value;
                    this.RaisePropertyChanged("Anvandare2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR Anvandare2Reference {
            get {
                return this.Anvandare2ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.Anvandare2ReferenceField, value) != true)) {
                    this.Anvandare2ReferenceField = value;
                    this.RaisePropertyChanged("Anvandare2Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kontakt {
            get {
                return this.KontaktField;
            }
            set {
                if ((object.ReferenceEquals(this.KontaktField, value) != true)) {
                    this.KontaktField = value;
                    this.RaisePropertyChanged("Kontakt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Request {
            get {
                return this.RequestField;
            }
            set {
                if ((this.RequestField.Equals(value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Meddelande", Namespace="http://schemas.datacontract.org/2004/07/wcf", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Meddelande : Dating.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.Anvandare AnvandareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.Anvandare Anvandare1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR Anvandare1ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR AnvandareReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FranField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HarLastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InnehallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MedIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SkickatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TillField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amne {
            get {
                return this.AmneField;
            }
            set {
                if ((object.ReferenceEquals(this.AmneField, value) != true)) {
                    this.AmneField = value;
                    this.RaisePropertyChanged("Amne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.Anvandare Anvandare {
            get {
                return this.AnvandareField;
            }
            set {
                if ((object.ReferenceEquals(this.AnvandareField, value) != true)) {
                    this.AnvandareField = value;
                    this.RaisePropertyChanged("Anvandare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.Anvandare Anvandare1 {
            get {
                return this.Anvandare1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Anvandare1Field, value) != true)) {
                    this.Anvandare1Field = value;
                    this.RaisePropertyChanged("Anvandare1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR Anvandare1Reference {
            get {
                return this.Anvandare1ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.Anvandare1ReferenceField, value) != true)) {
                    this.Anvandare1ReferenceField = value;
                    this.RaisePropertyChanged("Anvandare1Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR AnvandareReference {
            get {
                return this.AnvandareReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.AnvandareReferenceField, value) != true)) {
                    this.AnvandareReferenceField = value;
                    this.RaisePropertyChanged("AnvandareReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fran {
            get {
                return this.FranField;
            }
            set {
                if ((object.ReferenceEquals(this.FranField, value) != true)) {
                    this.FranField = value;
                    this.RaisePropertyChanged("Fran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HarLast {
            get {
                return this.HarLastField;
            }
            set {
                if ((this.HarLastField.Equals(value) != true)) {
                    this.HarLastField = value;
                    this.RaisePropertyChanged("HarLast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Innehall {
            get {
                return this.InnehallField;
            }
            set {
                if ((object.ReferenceEquals(this.InnehallField, value) != true)) {
                    this.InnehallField = value;
                    this.RaisePropertyChanged("Innehall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MedID {
            get {
                return this.MedIDField;
            }
            set {
                if ((this.MedIDField.Equals(value) != true)) {
                    this.MedIDField = value;
                    this.RaisePropertyChanged("MedID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Skickat {
            get {
                return this.SkickatField;
            }
            set {
                if ((this.SkickatField.Equals(value) != true)) {
                    this.SkickatField = value;
                    this.RaisePropertyChanged("Skickat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Till {
            get {
                return this.TillField;
            }
            set {
                if ((object.ReferenceEquals(this.TillField, value) != true)) {
                    this.TillField = value;
                    this.RaisePropertyChanged("Till");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfilBild", Namespace="http://schemas.datacontract.org/2004/07/wcf", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ProfilBild : Dating.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnvandareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.Anvandare Anvandare1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR Anvandare1ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BildField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BildIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anvandare {
            get {
                return this.AnvandareField;
            }
            set {
                if ((object.ReferenceEquals(this.AnvandareField, value) != true)) {
                    this.AnvandareField = value;
                    this.RaisePropertyChanged("Anvandare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.Anvandare Anvandare1 {
            get {
                return this.Anvandare1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Anvandare1Field, value) != true)) {
                    this.Anvandare1Field = value;
                    this.RaisePropertyChanged("Anvandare1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR Anvandare1Reference {
            get {
                return this.Anvandare1ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.Anvandare1ReferenceField, value) != true)) {
                    this.Anvandare1ReferenceField = value;
                    this.RaisePropertyChanged("Anvandare1Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bild {
            get {
                return this.BildField;
            }
            set {
                if ((object.ReferenceEquals(this.BildField, value) != true)) {
                    this.BildField = value;
                    this.RaisePropertyChanged("Bild");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BildID {
            get {
                return this.BildIDField;
            }
            set {
                if ((this.BildIDField.Equals(value) != true)) {
                    this.BildIDField = value;
                    this.RaisePropertyChanged("BildID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfAnvandarermld6wJR", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfAnvandarermld6wJR : Dating.ServiceReference1.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.Inlagg[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.Inlagg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.Anvandare))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.Kontakter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.Kontakter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.Meddelande[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.Meddelande))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.ProfilBild[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.ProfilBild))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR))]
    public partial class EntityReference : Dating.ServiceReference1.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dating.ServiceReference1.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dating.ServiceReference1.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dating.ServiceReference1.EntityReferenceOfAnvandarermld6wJR))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showWall", ReplyAction="http://tempuri.org/IService1/showWallResponse")]
        Dating.ServiceReference1.Inlagg[] showWall(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveInlagg", ReplyAction="http://tempuri.org/IService1/saveInlaggResponse")]
        void saveInlagg(Dating.ServiceReference1.Inlagg e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPicture", ReplyAction="http://tempuri.org/IService1/getPictureResponse")]
        Dating.ServiceReference1.ProfilBild[] getPicture(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProfilePicture", ReplyAction="http://tempuri.org/IService1/getProfilePictureResponse")]
        string getProfilePicture(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/savePicture", ReplyAction="http://tempuri.org/IService1/savePictureResponse")]
        void savePicture(string filePath, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendMail", ReplyAction="http://tempuri.org/IService1/sendMailResponse")]
        void sendMail(Dating.ServiceReference1.Meddelande e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getMails", ReplyAction="http://tempuri.org/IService1/getMailsResponse")]
        Dating.ServiceReference1.Meddelande[] getMails(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteMail", ReplyAction="http://tempuri.org/IService1/deleteMailResponse")]
        void deleteMail(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setIsRead", ReplyAction="http://tempuri.org/IService1/setIsReadResponse")]
        void setIsRead(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updatePerson", ReplyAction="http://tempuri.org/IService1/updatePersonResponse")]
        void updatePerson(Dating.ServiceReference1.Anvandare a, string currenUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/savePerson", ReplyAction="http://tempuri.org/IService1/savePersonResponse")]
        void savePerson(string user, string fnamn, string enamn, int Alder, string ort, string kon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPerson", ReplyAction="http://tempuri.org/IService1/getPersonResponse")]
        Dating.ServiceReference1.Anvandare getPerson(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addFriendRequest", ReplyAction="http://tempuri.org/IService1/addFriendRequestResponse")]
        void addFriendRequest(string toUser, string currentUser, int answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteFriendRequest", ReplyAction="http://tempuri.org/IService1/deleteFriendRequestResponse")]
        void deleteFriendRequest(string user, string kontaktUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getKontakter", ReplyAction="http://tempuri.org/IService1/getKontakterResponse")]
        Dating.ServiceReference1.Kontakter[] getKontakter(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modifyKontakt", ReplyAction="http://tempuri.org/IService1/modifyKontaktResponse")]
        void modifyKontakt(string user, string kontaktUser, int answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteKontakt", ReplyAction="http://tempuri.org/IService1/deleteKontaktResponse")]
        void deleteKontakt(string user, string kontaktUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPreviews", ReplyAction="http://tempuri.org/IService1/getPreviewsResponse")]
        Dating.ServiceReference1.ProfilBild[] getPreviews();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProfileNames", ReplyAction="http://tempuri.org/IService1/getProfileNamesResponse")]
        string[] getProfileNames();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Dating.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Dating.ServiceReference1.IService1>, Dating.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Dating.ServiceReference1.Inlagg[] showWall(string user) {
            return base.Channel.showWall(user);
        }
        
        public void saveInlagg(Dating.ServiceReference1.Inlagg e) {
            base.Channel.saveInlagg(e);
        }
        
        public Dating.ServiceReference1.ProfilBild[] getPicture(string user) {
            return base.Channel.getPicture(user);
        }
        
        public string getProfilePicture(string user) {
            return base.Channel.getProfilePicture(user);
        }
        
        public void savePicture(string filePath, string user) {
            base.Channel.savePicture(filePath, user);
        }
        
        public void sendMail(Dating.ServiceReference1.Meddelande e) {
            base.Channel.sendMail(e);
        }
        
        public Dating.ServiceReference1.Meddelande[] getMails(string user) {
            return base.Channel.getMails(user);
        }
        
        public void deleteMail(int ID) {
            base.Channel.deleteMail(ID);
        }
        
        public void setIsRead(int ID) {
            base.Channel.setIsRead(ID);
        }
        
        public void updatePerson(Dating.ServiceReference1.Anvandare a, string currenUser) {
            base.Channel.updatePerson(a, currenUser);
        }
        
        public void savePerson(string user, string fnamn, string enamn, int Alder, string ort, string kon) {
            base.Channel.savePerson(user, fnamn, enamn, Alder, ort, kon);
        }
        
        public Dating.ServiceReference1.Anvandare getPerson(string user) {
            return base.Channel.getPerson(user);
        }
        
        public void addFriendRequest(string toUser, string currentUser, int answer) {
            base.Channel.addFriendRequest(toUser, currentUser, answer);
        }
        
        public void deleteFriendRequest(string user, string kontaktUser) {
            base.Channel.deleteFriendRequest(user, kontaktUser);
        }
        
        public Dating.ServiceReference1.Kontakter[] getKontakter(string user) {
            return base.Channel.getKontakter(user);
        }
        
        public void modifyKontakt(string user, string kontaktUser, int answer) {
            base.Channel.modifyKontakt(user, kontaktUser, answer);
        }
        
        public void deleteKontakt(string user, string kontaktUser) {
            base.Channel.deleteKontakt(user, kontaktUser);
        }
        
        public Dating.ServiceReference1.ProfilBild[] getPreviews() {
            return base.Channel.getPreviews();
        }
        
        public string[] getProfileNames() {
            return base.Channel.getProfileNames();
        }
    }
}
